# features.yml: paths and parameters for the features
---
host:
    dna: resources/reference/chrX_sub.fa.gz
    gtf: resources/reference/chrX_sub.gtf.gz

mags:
    - resources/mags/scybalocola_faecipullorum.fna.gz
    - resources/mags/acutalibacter_ornithocaccae.fna.gz
