# Run tests over snakefile workflow
---
name: Tests

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main, devel]
  pull_request:
    branches: [main, devel]

env:
  CACHE_NUMBER: 0  # Increment this number to invalidate the cache

jobs:

  Pre-Commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run pre-commit on all files
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files

  Testing:
    runs-on: ubuntu-latest
    needs:
      - Pre-Commit
    steps:
      - uses: actions/checkout@v3

      - name: Set cache date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Cache
        uses: actions/cache@v2
        with:
          path: .snakemake/conda
          key: snakemake-conda-${{ env.CACHE_NUMBER }}
          # key: snakemake-conda-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
        id: cache

      - name: Download environments
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .
          snakefile: workflow/Snakefile
          args: >
            --use-conda
            --conda-create-envs-only
            --conda-frontend mamba
            --cores 1

      - name: Test workflow
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .
          snakefile: workflow/Snakefile
          args: >
            --use-conda
            --show-failed-logs
            --cores 3
            --conda-cleanup-pkgs cache
            --all-temp
